export type UserRole =
  | 'SUPER_ADMIN' | 'ADMIN' | 'KEPALA_SEKOLAH' | 'WAKIL_KEPALA'
  | 'GURU' | 'WALI_KELAS' | 'SISWA' | 'ORANG_TUA'
  | 'STAFF_TU' | 'STAFF_KEUANGAN'
export type JenisKelamin = 'L' | 'P'
export type Agama = 'ISLAM'
export type NamaSemester = 'GANJIL' | 'GENAP'
export type Hari = 'SENIN' | 'SELASA' | 'RABU' | 'KAMIS' | 'JUMAT' | 'SABTU' | 'MINGGU'
export type StatusAbsensi = 'HADIR' | 'SAKIT' | 'IZIN' | 'ALPA' | 'TERLAMBAT' | 'TAP'
export type ModeSesi = 'QR_LURING' | 'QR_WFH' | 'MANUAL'
export type StatusSesi = 'BELUM_BUKA' | 'AKTIF' | 'SELESAI' | 'EXPIRED'
export type StatusTagihan = 'BELUM_BAYAR' | 'CICILAN' | 'LUNAS' | 'TERLAMBAT'
export type StatusPembayaran = 'PENDING' | 'VERIFIED' | 'REJECTED'
export type MetodePembayaran = 'TUNAI' | 'TRANSFER' | 'VIRTUAL_ACCOUNT' | 'QRIS' | 'EDC' | 'MOBILE_BANKING'
export type TingkatLomba = 'SEKOLAH' | 'KECAMATAN' | 'KABUPATEN_KOTA' | 'PROVINSI' | 'NASIONAL' | 'INTERNASIONAL'
export type HasilPrestasi = 'JUARA_1' | 'JUARA_2' | 'JUARA_3' | 'JUARA_HARAPAN' | 'FINALIS' | 'PESERTA' | 'LAINNYA'
export type StatusPerizinan = 'PENDING' | 'APPROVED' | 'REJECTED' | 'REVISION_REQUESTED'
export type JenisPerizinan = 'SAKIT' | 'IZIN' | 'CUTI' | 'DINAS' | 'KEPERLUAN_KELUARGA'
export type StatusBerita = 'DRAFT' | 'PUBLISHED'
export type Priority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT'
export type StatusPengumpulan = 'DRAFT' | 'SUBMITTED' | 'DINILAI' | 'REVISI'
export type JenisSikap = 'POSITIF' | 'NEGATIF'
export type StatusAnggota = 'AKTIF' | 'NONAKTIF' | 'KELUAR'
export type StatusBiodata = 'DRAFT' | 'SUBMITTED' | 'DIVERIFIKASI' | 'DITOLAK'
export type StatusAkhirTahun = 'NAIK_KELAS' | 'TIDAK_NAIK' | 'LULUS' | 'DO' | 'MENGUNDURKAN_DIRI'
export type TipeKalender = 'LIBUR_NASIONAL' | 'LIBUR_SEKOLAH' | 'UJIAN' | 'KEGIATAN_SEKOLAH' | 'RAPAT' | 'LAINNYA'
export type TipeNotifikasi = 'INFO' | 'TUGAS' | 'PENILAIAN' | 'PEMBAYARAN' | 'ABSENSI' | 'PENGUMUMAN' | 'SIKAP' | 'PERIZINAN' | 'EKSTRAKURIKULER' | 'SISTEM'
export type JenisDokumen = 'CP' | 'ATP' | 'MODUL_AJAR_RPP' | 'MODUL_PROJEK_P5' | 'KKTP' | 'RINCIAN_MINGGU_EFEKTIF' | 'BUKU_PEGANGAN' | 'LAINNYA'
export type StatusDokumenPengajaran = 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'REVISION_REQUESTED'
