import os

ROOT = r"D:\projects\LMS-MAN\Code\nextjslms\src"

FILES = {}

# ─────────────────────────────────────────────────────────────────────────────
# 1. types/enums.ts — TAMBAH ModeSesi
# ─────────────────────────────────────────────────────────────────────────────
FILES["types/enums.ts"] = (
    "export type UserRole =\n"
    "  | 'SUPER_ADMIN' | 'ADMIN' | 'KEPALA_SEKOLAH' | 'WAKIL_KEPALA'\n"
    "  | 'GURU' | 'WALI_KELAS' | 'SISWA' | 'ORANG_TUA'\n"
    "  | 'STAFF_TU' | 'STAFF_KEUANGAN'\n"
    "export type JenisKelamin = 'L' | 'P'\n"
    "export type Agama = 'ISLAM'\n"
    "export type NamaSemester = 'GANJIL' | 'GENAP'\n"
    "export type Hari = 'SENIN' | 'SELASA' | 'RABU' | 'KAMIS' | 'JUMAT' | 'SABTU' | 'MINGGU'\n"
    "export type StatusAbsensi = 'HADIR' | 'SAKIT' | 'IZIN' | 'ALPA' | 'TERLAMBAT' | 'TAP'\n"
    "export type ModeSesi = 'QR_LURING' | 'QR_WFH' | 'MANUAL'\n"
    "export type StatusTagihan = 'BELUM_BAYAR' | 'CICILAN' | 'LUNAS' | 'TERLAMBAT'\n"
    "export type StatusPembayaran = 'PENDING' | 'VERIFIED' | 'REJECTED'\n"
    "export type MetodePembayaran = 'TUNAI' | 'TRANSFER' | 'VIRTUAL_ACCOUNT' | 'QRIS' | 'EDC' | 'MOBILE_BANKING'\n"
    "export type TingkatLomba = 'SEKOLAH' | 'KECAMATAN' | 'KABUPATEN_KOTA' | 'PROVINSI' | 'NASIONAL' | 'INTERNASIONAL'\n"
    "export type HasilPrestasi = 'JUARA_1' | 'JUARA_2' | 'JUARA_3' | 'JUARA_HARAPAN' | 'FINALIS' | 'PESERTA' | 'LAINNYA'\n"
    "export type StatusPerizinan = 'PENDING' | 'APPROVED' | 'REJECTED'\n"
    "export type JenisPerizinan = 'SAKIT' | 'IZIN' | 'CUTI' | 'DINAS' | 'KEPERLUAN_KELUARGA'\n"
    "export type StatusBerita = 'DRAFT' | 'PUBLISHED'\n"
    "export type Priority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT'\n"
    "export type StatusPengumpulan = 'DRAFT' | 'SUBMITTED' | 'DINILAI' | 'REVISI'\n"
    "export type JenisSikap = 'POSITIF' | 'NEGATIF'\n"
    "export type StatusAnggota = 'AKTIF' | 'NONAKTIF' | 'KELUAR'\n"
    "export type StatusBiodata = 'DRAFT' | 'SUBMITTED' | 'DIVERIFIKASI' | 'DITOLAK'\n"
    "export type StatusAkhirTahun = 'NAIK_KELAS' | 'TIDAK_NAIK' | 'LULUS' | 'DO' | 'MENGUNDURKAN_DIRI'\n"
    "export type TipeKalender = 'LIBUR_NASIONAL' | 'LIBUR_SEKOLAH' | 'UJIAN' | 'KEGIATAN_SEKOLAH' | 'RAPAT' | 'LAINNYA'\n"
    "export type TipeNotifikasi = 'INFO' | 'TUGAS' | 'PENILAIAN' | 'PEMBAYARAN' | 'ABSENSI' | 'PENGUMUMAN' | 'SIKAP' | 'PERIZINAN' | 'EKSTRAKURIKULER' | 'SISTEM'\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# 2. types/index.ts — TAMBAH export absensi & perizinan
# ─────────────────────────────────────────────────────────────────────────────
FILES["types/index.ts"] = (
    "export * from './api.types'\n"
    "export * from './auth.types'\n"
    "export * from './enums'\n"
    "export * from './users.types'\n"
    "export * from './tahun-ajaran.types'\n"
    "export * from './akademik.types'\n"
    "export * from './absensi.types'\n"
    "export * from './perizinan.types'\n"
    "export type { PaginatedResponse } from './api.types'\n"
    "export type { NamaSemester } from './enums'\n"
    "export type { UserRole } from './enums'\n"
    "export type { ModeSesi } from './enums'\n"
    "export type { AuthUser } from './auth.types'\n"
    "export type { LoginDto, LoginResponse, RefreshResponse } from './auth.types'\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# 3. types/absensi.types.ts — BARU
# ─────────────────────────────────────────────────────────────────────────────
FILES["types/absensi.types.ts"] = (
    "import type { StatusAbsensi, ModeSesi } from './enums'\n"
    "\n"
    "// ── Sesi ──────────────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface BukaSesiPayload {\n"
    "  jadwalPelajaranId: string\n"
    "  tanggal: string\n"
    "  durasiMenit: number\n"
    "  toleransiMenit: number\n"
    "  requireGps: boolean\n"
    "  latitudeGuru?: number\n"
    "  longitudeGuru?: number\n"
    "  radiusMeter?: number\n"
    "}\n"
    "\n"
    "export interface SesiResponse {\n"
    "  token: string\n"
    "  guruId: string\n"
    "  jadwalPelajaranId: string\n"
    "  kelasId: string\n"
    "  semesterId: string\n"
    "  mataPelajaranId: string\n"
    "  tanggal: string\n"
    "  jamMulai: string\n"
    "  toleransiMenit: number\n"
    "  mode: ModeSesi\n"
    "  requireGps: boolean\n"
    "  latitudeGuru?: number\n"
    "  longitudeGuru?: number\n"
    "  radiusMeter?: number\n"
    "  expiresAt: string\n"
    "  ttlDetik: number\n"
    "}\n"
    "\n"
    "export interface SesiDetail {\n"
    "  token: string\n"
    "  guruId: string\n"
    "  jadwalPelajaranId: string\n"
    "  kelasId: string\n"
    "  mataPelajaranId: string\n"
    "  tanggal: string\n"
    "  jamMulai: string\n"
    "  toleransiMenit: number\n"
    "  mode: ModeSesi\n"
    "  requireGps: boolean\n"
    "  radiusMeter?: number\n"
    "  expiresAt: string\n"
    "}\n"
    "\n"
    "export interface PesertaSesi {\n"
    "  id: string\n"
    "  nama: string\n"
    "  absen: number\n"
    "  sudahScan: boolean\n"
    "  statusSiswa: string\n"
    "  isEligible: boolean\n"
    "}\n"
    "\n"
    "export interface StatistikSesi {\n"
    "  total: number\n"
    "  hadir: number\n"
    "  sisa: number\n"
    "}\n"
    "\n"
    "export interface SesiDetailResponse {\n"
    "  sesi: SesiDetail\n"
    "  statistik: StatistikSesi\n"
    "  peserta: PesertaSesi[]\n"
    "}\n"
    "\n"
    "// ── My Status Hari Ini ────────────────────────────────────────────────────────\n"
    "\n"
    "export interface KelasWali {\n"
    "  id: string\n"
    "  namaKelas: string\n"
    "}\n"
    "\n"
    "export interface JadwalHariIniItem {\n"
    "  jadwalId: string\n"
    "  namaMapel: string\n"
    "  jam: string\n"
    "  isOngoing: boolean\n"
    "  statusAbsensi: string\n"
    "  modeSesi: ModeSesi | null\n"
    "}\n"
    "\n"
    "export interface MyStatusHariIniResponse {\n"
    "  isWaliKelas: boolean\n"
    "  kelasWali: KelasWali[]\n"
    "  total: number\n"
    "  data: JadwalHariIniItem[]\n"
    "}\n"
    "\n"
    "// ── Scan ──────────────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface ScanPayload {\n"
    "  token: string\n"
    "  latitude?: number\n"
    "  longitude?: number\n"
    "}\n"
    "\n"
    "export interface ScanResponse {\n"
    "  message: string\n"
    "  status: StatusAbsensi\n"
    "}\n"
    "\n"
    "// ── Manual Bulk ───────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface AbsensiManualItem {\n"
    "  userId: string\n"
    "  status: StatusAbsensi\n"
    "  keterangan?: string\n"
    "}\n"
    "\n"
    "export interface ManualBulkPayload {\n"
    "  jadwalPelajaranId: string\n"
    "  tanggal: string\n"
    "  absensi: AbsensiManualItem[]\n"
    "}\n"
    "\n"
    "// ── Override ──────────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface OverridePayload {\n"
    "  status: StatusAbsensi\n"
    "  keterangan?: string\n"
    "}\n"
    "\n"
    "// ── Matrix ────────────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface MatrixMetadata {\n"
    "  namaMapel: string\n"
    "  targetPertemuan: number | null\n"
    "  realisasiPertemuan: number\n"
    "}\n"
    "\n"
    "export interface MatrixSiswaSummary {\n"
    "  H: number\n"
    "  I: number\n"
    "  S: number\n"
    "  A: number\n"
    "}\n"
    "\n"
    "export interface MatrixSiswaRow {\n"
    "  no: number\n"
    "  nama: string\n"
    "  nisn: string\n"
    "  kehadiran: (string | null)[]\n"
    "  summary: MatrixSiswaSummary\n"
    "}\n"
    "\n"
    "export interface MatrixResponse {\n"
    "  metadata: MatrixMetadata\n"
    "  listPertemuan: (string | null)[]\n"
    "  dataSiswa: MatrixSiswaRow[]\n"
    "}\n"
    "\n"
    "// ── Reports ───────────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface SiswaKritisItem {\n"
    "  userId: string\n"
    "  nama: string\n"
    "  nisn: string\n"
    "  jumlahAlpa: number\n"
    "  kelasNama: string\n"
    "}\n"
    "\n"
    "export interface GuruDetailReport {\n"
    "  guruId: string\n"
    "  nama: string\n"
    "  statusKepatuhan: string\n"
    "  persentaseHadir: number\n"
    "  totalJP: number\n"
    "}\n"
    "\n"
    "export interface RekapHonorItem {\n"
    "  bulan: number\n"
    "  totalJP: number\n"
    "  bobot: number\n"
    "  nominal: number\n"
    "}\n"
    "\n"
    "// ── Sesi Actions ──────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface PerpanjangPayload {\n"
    "  tambahanMenit: number\n"
    "}\n"
    "\n"
    "// ── Public Stats ──────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface PublicStatsMonitoring {\n"
    "  jamSekarang: string\n"
    "  totalJadwalSeharusnya: number\n"
    "  totalSesiAktif: number\n"
    "  persentaseKBM: number\n"
    "}\n"
    "\n"
    "export interface PublicStatsLiveItem {\n"
    "  mapel: string\n"
    "  kelas: string\n"
    "  status: string\n"
    "}\n"
    "\n"
    "export interface PublicStatsKehadiran {\n"
    "  status: string\n"
    "  _count: number\n"
    "}\n"
    "\n"
    "export interface PublicStatsAchievement {\n"
    "  label: string\n"
    "  topList: string[]\n"
    "}\n"
    "\n"
    "export interface PublicStatsResponse {\n"
    "  monitoring: PublicStatsMonitoring\n"
    "  liveList: PublicStatsLiveItem[]\n"
    "  sekolah: {\n"
    "    kehadiranHariIni: PublicStatsKehadiran[]\n"
    "    updateTerakhir: string\n"
    "  }\n"
    "  achievement: PublicStatsAchievement\n"
    "}\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# 4. types/perizinan.types.ts — BARU
# ─────────────────────────────────────────────────────────────────────────────
FILES["types/perizinan.types.ts"] = (
    "import type { StatusPerizinan, JenisPerizinan } from './enums'\n"
    "\n"
    "export interface PerizinanPayload {\n"
    "  userId: string\n"
    "  jenis: JenisPerizinan\n"
    "  tanggalMulai: string\n"
    "  tanggalSelesai: string\n"
    "  alasan: string\n"
    "  fileBuktiUrl?: string\n"
    "}\n"
    "\n"
    "export interface PerizinanUserProfile {\n"
    "  namaLengkap: string\n"
    "}\n"
    "\n"
    "export interface PerizinanUser {\n"
    "  profile?: PerizinanUserProfile\n"
    "}\n"
    "\n"
    "export interface PerizinanItem {\n"
    "  id: string\n"
    "  userId: string\n"
    "  jenis: JenisPerizinan\n"
    "  tanggalMulai: string\n"
    "  tanggalSelesai: string\n"
    "  alasan: string\n"
    "  fileBuktiUrl?: string\n"
    "  status: StatusPerizinan\n"
    "  catatanApproval?: string\n"
    "  approvedBy?: string\n"
    "  createdAt: string\n"
    "  updatedAt: string\n"
    "  user?: PerizinanUser\n"
    "}\n"
    "\n"
    "export interface PerizinanMeta {\n"
    "  total: number\n"
    "  page: number\n"
    "  limit: number\n"
    "  lastPage: number\n"
    "}\n"
    "\n"
    "export interface PerizinanListResponse {\n"
    "  data: PerizinanItem[]\n"
    "  meta: PerizinanMeta\n"
    "}\n"
    "\n"
    "export interface PerizinanApprovalPayload {\n"
    "  status: StatusPerizinan\n"
    "  catatanApproval?: string\n"
    "}\n"
    "\n"
    "export interface PerizinanRevisiPayload {\n"
    "  alasan?: string\n"
    "  jenis?: JenisPerizinan\n"
    "}\n"
    "\n"
    "export interface PerizinanQueryParams {\n"
    "  page?: number\n"
    "  limit?: number\n"
    "  userId?: string\n"
    "  jenis?: JenisPerizinan\n"
    "  status?: StatusPerizinan\n"
    "  tanggalMulai?: string\n"
    "  tanggalSelesai?: string\n"
    "}\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# 5. lib/api/absensi.api.ts — BARU
# ─────────────────────────────────────────────────────────────────────────────
FILES["lib/api/absensi.api.ts"] = (
    "import api from '@/lib/axios'\n"
    "import type {\n"
    "  BukaSesiPayload,\n"
    "  SesiResponse,\n"
    "  SesiDetailResponse,\n"
    "  ScanPayload,\n"
    "  ScanResponse,\n"
    "  ManualBulkPayload,\n"
    "  OverridePayload,\n"
    "  MatrixResponse,\n"
    "  MyStatusHariIniResponse,\n"
    "  SiswaKritisItem,\n"
    "  GuruDetailReport,\n"
    "  PerpanjangPayload,\n"
    "  PublicStatsResponse,\n"
    "} from '@/types'\n"
    "\n"
    "// ── Sesi ─────────────────────────────────────────────────────────────────────\n"
    "\n"
    "export const bukaSesi = (payload: BukaSesiPayload) =>\n"
    "  api.post<SesiResponse>('/absensi/sesi', payload).then((r) => r.data)\n"
    "\n"
    "export const getSesiDetail = (token: string) =>\n"
    "  api.get<SesiDetailResponse>(`/absensi/sesi/${token}`).then((r) => r.data)\n"
    "\n"
    "export const perpanjangSesi = (token: string, payload: PerpanjangPayload) =>\n"
    "  api.patch(`/absensi/sesi/${token}/perpanjang`, payload).then((r) => r.data)\n"
    "\n"
    "export const tutupSesi = (token: string) =>\n"
    "  api.patch(`/absensi/sesi/${token}/tutup`).then((r) => r.data)\n"
    "\n"
    "// ── Scan (Siswa) ──────────────────────────────────────────────────────────────\n"
    "\n"
    "export const scanQR = (payload: ScanPayload) =>\n"
    "  api.post<ScanResponse>('/absensi/scan', payload).then((r) => r.data)\n"
    "\n"
    "// ── My Endpoints ──────────────────────────────────────────────────────────────\n"
    "\n"
    "export const getMyStatusHariIni = (semesterId: string) =>\n"
    "  api\n"
    "    .get<MyStatusHariIniResponse>('/absensi/my/status-hari-ini', {\n"
    "      params: { semesterId },\n"
    "    })\n"
    "    .then((r) => r.data)\n"
    "\n"
    "// ── Manual Bulk ───────────────────────────────────────────────────────────────\n"
    "\n"
    "export const simpanManualBulk = (payload: ManualBulkPayload) =>\n"
    "  api.post('/absensi/manual/bulk', payload).then((r) => r.data)\n"
    "\n"
    "// ── Override ──────────────────────────────────────────────────────────────────\n"
    "\n"
    "export const overrideAbsensi = (id: string, payload: OverridePayload) =>\n"
    "  api.patch(`/absensi/${id}/override`, payload).then((r) => r.data)\n"
    "\n"
    "// ── Matrix ────────────────────────────────────────────────────────────────────\n"
    "\n"
    "export interface MatrixQueryParams {\n"
    "  kelasId: string\n"
    "  mataPelajaranId: string\n"
    "  semesterId: string\n"
    "}\n"
    "\n"
    "export const getMatrixRekap = (params: MatrixQueryParams) =>\n"
    "  api.get<MatrixResponse>('/absensi/rekap/matrix', { params }).then((r) => r.data)\n"
    "\n"
    "export const exportMatrix = (params: MatrixQueryParams) =>\n"
    "  api.get<Blob>('/absensi/export/matrix', { params, responseType: 'blob' })\n"
    "\n"
    "// ── Reports ───────────────────────────────────────────────────────────────────\n"
    "\n"
    "export const getSiswaKritis = (semesterId: string) =>\n"
    "  api\n"
    "    .get<SiswaKritisItem[]>('/absensi-report/siswa/kritis', {\n"
    "      params: { semesterId },\n"
    "    })\n"
    "    .then((r) => r.data)\n"
    "\n"
    "export const getGuruDetail = (guruId: string, semesterId: string) =>\n"
    "  api\n"
    "    .get<GuruDetailReport>(`/absensi-report/guru/detail/${guruId}`, {\n"
    "      params: { semesterId },\n"
    "    })\n"
    "    .then((r) => r.data)\n"
    "\n"
    "export const getRekapHonorGuru = (\n"
    "  guruId: string,\n"
    "  semesterId: string,\n"
    "  bulan: number,\n"
    ") =>\n"
    "  api\n"
    "    .get(`/absensi/rekap/guru/${guruId}`, { params: { semesterId, bulan } })\n"
    "    .then((r) => r.data)\n"
    "\n"
    "export const getSiswaYearly = () =>\n"
    "  api.get('/absensi-report/siswa/yearly').then((r) => r.data)\n"
    "\n"
    "export const getSiswaPerTingkat = () =>\n"
    "  api.get('/absensi-report/siswa/per-tingkat').then((r) => r.data)\n"
    "\n"
    "export const getSiswaPerKelas = (kelasId: string) =>\n"
    "  api.get(`/absensi-report/siswa/per-kelas/${kelasId}`).then((r) => r.data)\n"
    "\n"
    "export const getSiswaDetailReport = (siswaId: string) =>\n"
    "  api.get(`/absensi-report/siswa/detail/${siswaId}`).then((r) => r.data)\n"
    "\n"
    "// ── Public ────────────────────────────────────────────────────────────────────\n"
    "\n"
    "export const getPublicStats = () =>\n"
    "  api.get<PublicStatsResponse>('/absensi-public/stats').then((r) => r.data)\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# 6. lib/api/perizinan.api.ts — BARU
# ─────────────────────────────────────────────────────────────────────────────
FILES["lib/api/perizinan.api.ts"] = (
    "import api from '@/lib/axios'\n"
    "import type {\n"
    "  PerizinanPayload,\n"
    "  PerizinanItem,\n"
    "  PerizinanListResponse,\n"
    "  PerizinanApprovalPayload,\n"
    "  PerizinanRevisiPayload,\n"
    "  PerizinanQueryParams,\n"
    "} from '@/types'\n"
    "\n"
    "export const ajukanPerizinan = (payload: PerizinanPayload) =>\n"
    "  api.post<PerizinanItem>('/perizinan', payload).then((r) => r.data)\n"
    "\n"
    "export const getListPerizinan = (params: PerizinanQueryParams) =>\n"
    "  api\n"
    "    .get<PerizinanListResponse>('/perizinan', { params })\n"
    "    .then((r) => r.data)\n"
    "\n"
    "export const getDetailPerizinan = (id: string) =>\n"
    "  api.get<PerizinanItem>(`/perizinan/${id}`).then((r) => r.data)\n"
    "\n"
    "export const revisiPerizinan = (id: string, payload: PerizinanRevisiPayload) =>\n"
    "  api.patch<PerizinanItem>(`/perizinan/${id}`, payload).then((r) => r.data)\n"
    "\n"
    "export const approvalPerizinan = (\n"
    "  id: string,\n"
    "  payload: PerizinanApprovalPayload,\n"
    ") =>\n"
    "  api\n"
    "    .patch<PerizinanItem>(`/perizinan/${id}/approval`, payload)\n"
    "    .then((r) => r.data)\n"
    "\n"
    "export const hapusPerizinan = (id: string) =>\n"
    "  api\n"
    "    .delete<{ message: string }>(`/perizinan/${id}`)\n"
    "    .then((r) => r.data)\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# WRITER
# ─────────────────────────────────────────────────────────────────────────────
def write_files():
    for relative_path, content in FILES.items():
        full_path = os.path.join(ROOT, relative_path.replace('/', os.sep))
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[OK] {relative_path}")

if __name__ == '__main__':
    write_files()
    print("\n✅ Batch 1 selesai — 6 file digenerate.")
    print("   Selanjutnya jalankan: npx tsc --noEmit 2>&1 | Select-String 'absensi|perizinan'")